version: '3'
services:
  database:
    image: postgres:11.2
    container_name: vrudi-db
    environment:
      POSTGRES_DB: vrudi
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
